spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  config:
    activate:
      on-profile: prod
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/ordermsa?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: ${DB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show_sql: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: aws-eks-frontend-image-143710973003-ap-northeast-2-an
