apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-depl
  namespace: soldesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
      labels:
        app: member
    spec:
      containers:
      - name: member-container
        image: 143710973003.dkr.ecr.ap-northeast-2.amazonaws.com/member-service:latest
        ports:
        - containerPort: 8080
        resources:
        # 컨테이너가 사용할수 있는 리소스의 최대치
          limits:
            cpu: "1"
            memory: "500Mi"
        # 컨테이너가 시작될떄 보장받아야 하는 최소 자원
          requests:
            cpu: "0.5"
            memory: "250Mi"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: my-app-secrets
              key: DB_PW
        # 컨테이너 상태 확인 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: soldesk
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: member
  