apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-syong-store-tls
  namespace: monitoring
spec:
  secretName: monitoring-syong-store-tls
  duration: 2160h      # 90d
  renewBefore: 360h    # 15d
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  dnsNames:
  - prometheus.syong.store
  - grafana.syong.store