apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yonginfra/msa.git
    targetRevision: main
    path: msa/k8s/k8s-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true